#!/usr/bin/env python3

from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys

from fuzzy_resf_core import (
    reconstruct_model,
    write_openings_csv,
    write_result_json,
    write_slabs_csv,
    write_walls_csv,
)
from ifc_export import write_ifc


def main() -> int:
    parser = argparse.ArgumentParser(description="qFuzzyRESF semantic Scan-to-BIM backend")
    parser.add_argument("--request", required=True, help="Path to the JSON request generated by the CloudCompare plugin")
    args = parser.parse_args()

    request_path = Path(args.request)
    request = json.loads(request_path.read_text(encoding="utf-8"))
    output_dir = Path(request["output"])
    output_dir.mkdir(parents=True, exist_ok=True)

    try:
        model, summary = reconstruct_model(request)
        write_walls_csv(model.walls, output_dir / "walls.csv")
        write_openings_csv(model.openings, output_dir / "openings.csv")
        write_slabs_csv(model.slabs, output_dir / "slabs.csv")

        if request.get("export_ifc", True):
            write_ifc(model, output_dir / "fuzzy_resf.ifc")

        summary["preset"] = request.get("preset", "Fuzzy-RESF")
        summary["walls_csv"] = str(output_dir / "walls.csv")
        summary["openings_csv"] = str(output_dir / "openings.csv")
        summary["slabs_csv"] = str(output_dir / "slabs.csv")
        summary["ifc"] = str(output_dir / "fuzzy_resf.ifc") if request.get("export_ifc", True) else None

        if summary["modeled_walls"] == 0:
            summary["warning"] = "No architectural walls were reconstructed; IFC may be incomplete."
        elif summary["doors"] == 0 and summary["windows"] == 0:
            summary["warning"] = (
                "Walls were reconstructed, but no reliable door/window openings were detected. "
                "This can occur when openings are occluded or wall sampling is too sparse."
            )

        write_result_json(summary, output_dir / "result.json")
        return 0
    except Exception as exc:
        error = {
            "status": "error",
            "method": "Fuzzy-RESF",
            "version": "1.1-semantic-bim",
            "error": f"{type(exc).__name__}: {exc}",
        }
        write_result_json(error, output_dir / "result.json")
        print(error["error"], file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
