#!/usr/bin/env python3

from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys

from bim_reconstruction import reconstruct_bim, write_csv, write_model_json
from ifc_bim_export import write_bim_ifc
from opening_refinement import refine_floor_connected_doors


def _write_summary(summary: dict, path: Path) -> None:
    path.write_text(json.dumps(summary, indent=2), encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description="qFuzzyRESF object-level BIM backend")
    parser.add_argument("--request", required=True, help="Path to the JSON request generated by the CloudCompare plugin")
    args = parser.parse_args()

    request_path = Path(args.request)
    request = json.loads(request_path.read_text(encoding="utf-8"))
    output_dir = Path(request["output"])
    output_dir.mkdir(parents=True, exist_ok=True)

    result_path = output_dir / "result.json"
    try:
        model = reconstruct_bim(request)
        if not model.walls:
            raise RuntimeError("No BIM wall objects were reconstructed; IFC export aborted")

        # Floor returns frequently mask the bottom row of a doorway in a binary wall
        # occupancy raster. A second, density-normalised pass searches explicitly for
        # floor-connected gaps with two jambs and a lintel.
        extra_doors = refine_floor_connected_doors(
            request["input"], model, float(request.get("raster_cell_m", 0.02))
        )
        if extra_doors:
            model.openings.extend(extra_doors)
            for i, opening in enumerate(model.openings, 1):
                opening.id = i

        model.summary["doors"] = sum(o.kind == "Door" for o in model.openings)
        model.summary["windows"] = sum(o.kind == "Window" for o in model.openings)
        model.summary["openings"] = len(model.openings)
        if model.openings:
            model.summary["warnings"] = [
                w for w in model.summary.get("warnings", [])
                if not w.startswith("No door/window openings")
            ]

        walls_path = output_dir / "walls.csv"
        openings_path = output_dir / "openings.csv"
        spaces_path = output_dir / "spaces.csv"
        slabs_path = output_dir / "slabs.csv"
        model_path = output_dir / "bim_model.json"
        ifc_path = output_dir / "fuzzy_resf.ifc"

        write_csv(model.walls, walls_path,
                  ["id","storey_id","x1","y1","x2","y2","z0","z1","thickness","theta_deg","confidence","support","continuity","source"])
        write_csv(model.openings, openings_path,
                  ["id","wall_id","storey_id","kind","offset","width","sill","height","confidence"])
        write_csv(model.spaces, spaces_path,
                  ["id","storey_id","name","polygon","z0","z1","area","confidence"])
        write_csv(model.slabs, slabs_path,
                  ["id","storey_id","kind","polygon","z","thickness","confidence"])
        write_model_json(model, model_path)

        if request.get("export_ifc", True):
            write_bim_ifc(model, ifc_path)
            if not ifc_path.exists() or ifc_path.stat().st_size < 1024:
                raise RuntimeError("IFC exporter produced an invalid or unexpectedly small file")

        summary = dict(model.summary)
        summary.update({
            "preset": request.get("preset", "Fuzzy-RESF-BIM"),
            "walls_csv": str(walls_path),
            "openings_csv": str(openings_path),
            "spaces_csv": str(spaces_path),
            "slabs_csv": str(slabs_path),
            "bim_model_json": str(model_path),
            "ifc": str(ifc_path) if request.get("export_ifc", True) else None,
        })
        _write_summary(summary, result_path)
        for warning in summary.get("warnings", []):
            print(f"WARNING: {warning}", file=sys.stderr)
        return 0
    except Exception as exc:
        error = {
            "status": "error",
            "method": "Fuzzy-RESF-BIM",
            "version": "2.0-object-bim",
            "error": f"{type(exc).__name__}: {exc}",
        }
        _write_summary(error, result_path)
        print(error["error"], file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
